version: '3.8'

services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector HTTP
      - "14250:14250"  # Jaeger collector gRPC
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  traceroot:
    build:
      context: ../../..
      dockerfile: ./docker/public/Dockerfile
      args:
        - LOCAL_BUILD=true
    container_name: traceroot
    ports:
      - "3000:3000"    # Frontend
      - "8000:8000"    # Backend API
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      jaeger:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "&&", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

networks:
  default:
    name: traceroot-network
